name: Auto commit

on:      
  schedule:
  - cron: "*/5 * * * *"
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
          # Use this username's contribution graph
          user_name: tienthuan05082002
          # Text on contribution graph
          text: noroom113
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update action output
          file_pattern: gitartwork.svg
          commit_user_name: noroom113
          commit_user_email: tienthuan05082002@gmail.com # defaults to "github-actions[bot]@users.noreply.github.com"
          commit_author: TienThuan <tienthuan05082002@gmail.com@gmail.com> # defaults to author of the commit that triggered the ru
